LOCAL_PATH := $(call my-dir)


include $(CLEAR_VARS)
LOCAL_MODULE := libaec
LOCAL_MODULE_TAGS := optional
LOCAL_VENDOR_MODULE := true
#LOCAL_SRC_FILES := 
LOCAL_SRC_FILES_32 := lib/libaec.so
LOCAL_SRC_FILES_64 := lib64/libaec.so
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := SHARED_LIBRARIES

include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
LOCAL_MODULE := libdownlink
LOCAL_MODULE_TAGS := optional
LOCAL_VENDOR_MODULE := true
#LOCAL_SRC_FILES := 
LOCAL_SRC_FILES_32 := lib/libdownlink.so
LOCAL_SRC_FILES_64 := lib64/libdownlink.so
LOCAL_MODULE_STEM_32 := $(LOCAL_MODULE)
LOCAL_MODULE_STEM_64 := $(LOCAL_MODULE)
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := both
LOCAL_MODULE_CLASS := SHARED_LIBRARIES

include $(BUILD_PREBUILT)

